name: Trying WF with if condition and dispatch options

on:
  workflow_dispatch:
    inputs:
      Required:
        description: 'Is this run neccessary?'
        required: true
        default: false
        type: boolean
      Message:
        description: 'Message goes here!'
        required: false
        default: 'Hello, World!'
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    if: ${{ inputs.Required }}
    #if/: github.ref == 'refs/heads/main'
    # Above statement checks if the event that triggered the workflow is a push to the main branch.
    # If need to match string then use double quotes around the string.
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run command
        run: echo "The input was:" ${{ inputs.Message }}
