name:  matrix configuration

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        images: [alpine, hello-world]
        exclude:
          - os: windows-latest
            images: alpine
    steps:
    - name: run
      run: echo "This is running on ${{ matrix.os }} with image ${{ matrix.images }}"