name:  matrix configuration

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 2
      # Fail-fast: If true, the matrix job will stop all other jobs in the matrix if one job fails.
      # Max-parallel: Maximum number of jobs that can run in parallel.
      matrix:
        os: [ubuntu-latest, windows-latest]
        images: [alpine, hello-world]
        exclude:
          - os: windows-latest
            images: alpine
    steps:
    - name: run
      run: echo "This is running on ${{ matrix.os }} with image ${{ matrix.images }}"