name: matrix config

on: 
    workflow_dispatch:
    push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        images: [hello-world, alpine]
        exclude:
        - os: ubuntu-latest
          images: [hello-world]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Docker
        run: docker info
      - name: Run Docker Container
        run: |
            docker run --rm ${{ matrix.images }}