name: upload download artifacts

on: push

jobs:
  first_job:
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: change permission
      run: chmod +x ./sh.sh

    - name: run sh script in first job
      run: bash ./sh.sh >> cowsay.log
    
    - uses: actions/upload-artifact@v4
      with:
        name: cowsay-log
        path: cowsay.log

  second_job:
    needs: first_job
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: second message
      run: |
        echo "this is message from second job"
        date    
    
    - uses: actions/download-artifact@v4
      with:
        name: cowsay-log
    
    - name: show cowsay log
      run: cat cowsay.log


  third_job:
    needs: [first_job, second_job]
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: third message
      run: |
        echo "this is message from third job"
        date