name: variable secrets

on: push

env:
  logfile: cowsay.log
  secret_message: ${{ secrets.SECRET_MESSAGE }}
  app_version: ${{ vars.APP_VERSION }}

# Environment variables can also be defined at job level and step levels.

jobs:
  first_job:
    runs-on: self-hosted
#    env: 
#      logfile: cowsay.log
    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: change permission
      run: chmod +x ./sh.sh

    - name: run sh script in first job
      env:
        logfile: cowsay.log
      run: bash ./sh.sh >> ${{ env.logfile }}
    
    - uses: actions/upload-artifact@v4
      with:
        name: cowsay-log
        path: ${{ env.logfile }}

  second_job:
    needs: first_job
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: second message
      run: |
        echo "this is message from second job"
        date    
    
    - uses: actions/download-artifact@v4
      with:
        name: cowsay-log
    
    - name: show cowsay log
      run: cat ${{ env.logfile }}


  third_job:
    needs: [first_job, second_job]
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: third message
      run: |
        echo "this is message from third job"
        echo Here goes the secret: ${{ env.secret_message }}
        echo Here goes the app version: ${{ env.app_version }}
        date